{% set name = "unordered_dense" %}
{% set version = "4.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/martinus/unordered_dense/archive/v{{ version }}.tar.gz
  sha256: 9f7202ec6d8353932ef865d33f5872e4b7a1356e9032da7cd09c3a0c5bb2b7de

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - pkg-config
    - gnuconfig
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/ankerl/unordered_dense.h                                                   # [unix]
    - test -f ${PREFIX}/lib/cmake/unordered_dense/unordered_denseTargets.cmake                             # [unix]
    - test -f ${PREFIX}/lib/cmake/unordered_dense/unordered_denseConfig.cmake                              # [unix]
    - test -f ${PREFIX}/lib/cmake/unordered_dense/unordered_denseConfigVersion.cmake                       # [unix]
    - if not exist %LIBRARY_PREFIX%\include\ankerl\unordered_dense.h (exit 1)                              # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\unordered_dense\unordered_denseTargets.cmake (exit 1)        # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\unordered_dense\unordered_denseConfig.cmake (exit 1)         # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\unordered_dense\unordered_denseConfigVersion.cmake (exit 1)  # [win]

about:
  summary: A fast & densely stored hashmap and hashset based on robin-hood backward shift deletion
  description: |
    A fast & densely stored hashmap and hashset based on robin-hood backward shift deletion for C++17 and later.

    The classes `ankerl::unordered_dense::map` and `ankerl::unordered_dense::set` are (almost) drop-in replacements
    of `std::unordered_map` and `std::unordered_set`.

    While they don't have as strong iterator / reference stability guaranties, they are typically much faster.

    Additionally, there are `ankerl::unordered_dense::segmented_map` and `ankerl::unordered_dense::segmented_set`
    with lower peak memory usage. and stable iterator/references on insert.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  home: https://github.com/martinus/unordered_dense
  dev_url: https://github.com/martinus/unordered_dense

extra:
  recipe-maintainers:
    - jjerphan
